package com.mycompany.myapp;


import com.codename1.components.ImageViewer;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Component;
import static com.codename1.ui.Component.CENTER;
import com.codename1.ui.Container;
import com.codename1.ui.Image;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.layouts.FlowLayout;
import com.mycompany.gui.LoginForm;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplicationUser {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() throws IOException {
        if(current != null){
            current.show();
            return;
        }
//        Form Login = new Form("", new FlowLayout(CENTER,CENTER));
//         
//Container c=new Container(new BoxLayout(BoxLayout.Y_AXIS));
//
//
//
//
//
//
//
//
// TextField nomutilisateur = new TextField();
//        nomutilisateur.setHint("Nom d'utilisateur");
//       
//        TextField mdp = new TextField("", "Mot de passe", 0, TextField.NUMERIC);
//        
//        mdp.setConstraint(TextField.PASSWORD );
//        
//        Button b1 = new Button("Se connecter");
//        
//        
//        Button b12 = new Button("S'inscrire");
//        
//        Label label = new Label("S'inscrire");
//        
//         b12.addActionListener(new ActionListener() {
//
//            @Override
//            public void actionPerformed(ActionEvent evt) {
//                
//                 //-----------------------INSCRIPTION--------------------------
//        
//        
//         Form Inscription = new Form("", new FlowLayout(CENTER,CENTER));
//         
//Container c1=new Container(new BoxLayout(BoxLayout.Y_AXIS));
//
//
//
//
//
//
//
//
// TextField username = new TextField();
//        username.setHint("Nom d'utilisateur");
//        
//         TextField nom = new TextField();
//        nom.setHint("Nom");
//        
//        
//         TextField prénom = new TextField();
//        prénom.setHint("Prénom");
//        
//        
//         TextField mail = new TextField();
//        mail.setHint("Adresse e-mail");
//        
//       
//        TextField mdp1 = new TextField("", "Mot de passe", 0, TextField.NUMERIC);
//        
//        mdp1.setConstraint(TextField.PASSWORD );
//        
//        TextField mdp12 = new TextField("", "Confirmer mot de passe", 0, TextField.NUMERIC);
//        
//        mdp12.setConstraint(TextField.PASSWORD );
//        
//        Button b11 = new Button("S'inscrire");
//        
//        
//         c1.add(username);
//        c1.add(nom);
//        c1.add(prénom);
//        c1.add(mail);
//        
//        c1.add(mdp1);
//        c1.add(mdp12);
//        c1.add(b11);
//                Inscription.add(c1);
//                
//                        Inscription.show();
//
//
//              }
//        });
//        
//        
//        
//        
//       
//        
////        ImageViewer tf1 = new ImageViewer();
////
////                    
////                        Image im1 = Image.createImage("/back.jpg");
////                        
////                       tf1.setImage(im1);
//        
//        c.add(nomutilisateur);
//        c.add(mdp);
//        c.add(b1);
//                c.add(b12);
//
//        Login.add(c);
//        
//        Login.show();
//       
//        //Login.add(tf1);


        LoginForm f = new LoginForm();
        f.getF().show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
